import type { Tool } from "../types";

// Demo-Datensatz. In Produktion ersetzt die tägliche Firebase Function
// (siehe /functions) diese Einträge durch aktuell recherchierte Tools.
export const seedTools: Tool[] = [
  {
    id: "claude",
    name: "Claude",
    categoryId: "ki",
    tagline: "KI-Assistent für Text, Code und Recherche",
    description:
      "Chat-Assistent von Anthropic mit starken Fähigkeiten in Analyse, Schreiben und Programmierung, verfügbar als App, im Browser und über API.",
    url: "https://claude.ai",
    priceTier: "freemium",
    priceDetail: "kostenlos, Pro ab 20€/Monat",
    trustScore: 92,
    sources: [{ name: "Anthropic", url: "https://anthropic.com" }],
    firstSeen: "2024-03-01",
    lastUpdated: new Date().toISOString(),
    isNew: false,
    tags: ["assistent", "produktivität", "entwicklung"],
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    categoryId: "ki",
    tagline: "KI-Notizbuch für eigene Dokumente",
    description:
      "Lädt eigene Quellen hoch und lässt sie durchsuchen, zusammenfassen und in Audio-Übersichten verwandeln.",
    url: "https://notebooklm.google",
    priceTier: "kostenlos",
    trustScore: 85,
    sources: [{ name: "Google", url: "https://google.com" }],
    firstSeen: "2024-07-01",
    lastUpdated: new Date().toISOString(),
    isNew: true,
    tags: ["recherche", "notizen"],
  },
  {
    id: "midjourney",
    name: "Midjourney",
    categoryId: "bilder",
    tagline: "Bildgenerator mit sehr hoher künstlerischer Qualität",
    description:
      "Gilt bei vielen als das Modell mit dem stärksten ästhetischen Ergebnis, bedient über Discord oder eigene Web-App, kein kostenloser Tarif mehr.",
    url: "https://midjourney.com",
    priceTier: "abo",
    priceDetail: "ab ca. 10€/Monat",
    trustScore: 89,
    sources: [{ name: "Midjourney", url: "https://midjourney.com" }],
    firstSeen: "2022-07-01",
    lastUpdated: new Date().toISOString(),
    tags: ["bildgenerierung", "kunst"],
  },
  {
    id: "chatgpt-images",
    name: "ChatGPT (Bildgenerierung)",
    categoryId: "bilder",
    tagline: "Bildgenerierung direkt im Chat, sehr gut im Befolgen von Text-Anweisungen",
    description:
      "In ChatGPT integrierte Bildgenerierung, besonders stark bei präzisem Befolgen komplexer Anweisungen und beim Einfügen von lesbarem Text ins Bild.",
    url: "https://chatgpt.com",
    priceTier: "freemium",
    priceDetail: "kostenlos mit Limit, Plus ab 20€/Monat",
    trustScore: 87,
    sources: [{ name: "OpenAI", url: "https://openai.com" }],
    firstSeen: "2025-03-01",
    lastUpdated: new Date().toISOString(),
    isNew: true,
    tags: ["bildgenerierung", "text-in-bild"],
  },
  {
    id: "nano-banana",
    name: "Gemini (Nano Banana)",
    categoryId: "bilder",
    tagline: "Googles Bildmodell mit starker Bildbearbeitung",
    description:
      "Besonders gut darin, bestehende Fotos gezielt zu verändern statt nur neue Bilder zu erzeugen, in Gemini und der Google-Suche integriert.",
    url: "https://gemini.google.com",
    priceTier: "freemium",
    trustScore: 84,
    sources: [{ name: "Google", url: "https://gemini.google.com" }],
    firstSeen: "2025-08-01",
    lastUpdated: new Date().toISOString(),
    isNew: true,
    tags: ["bildgenerierung", "bildbearbeitung"],
  },
  {
    id: "flux",
    name: "FLUX (Black Forest Labs)",
    categoryId: "bilder",
    tagline: "Offenes Bildmodell, auch lokal betreibbar",
    description:
      "Quelloffene Modellfamilie, die sich selbst hosten lässt und in vielen Drittanbieter-Tools als Basis dient, gute Bildqualität bei freier Nutzung.",
    url: "https://blackforestlabs.ai",
    priceTier: "kostenlos",
    priceDetail: "Open Weights, gehostete Varianten kostenpflichtig",
    trustScore: 81,
    sources: [{ name: "Black Forest Labs", url: "https://blackforestlabs.ai" }],
    firstSeen: "2024-08-01",
    lastUpdated: new Date().toISOString(),
    tags: ["bildgenerierung", "open-source"],
  },
  {
    id: "home-assistant",
    name: "Home Assistant",
    categoryId: "haushalt",
    tagline: "Offene Smart-Home-Zentrale",
    description:
      "Verbindet Smart-Home-Geräte verschiedener Hersteller lokal und ohne Cloud-Zwang in einer Oberfläche.",
    url: "https://www.home-assistant.io",
    priceTier: "kostenlos",
    trustScore: 88,
    sources: [{ name: "Home Assistant", url: "https://home-assistant.io" }],
    firstSeen: "2023-01-01",
    lastUpdated: new Date().toISOString(),
    tags: ["smart-home", "automatisierung"],
  },
  {
    id: "tody",
    name: "Tody",
    categoryId: "haushalt",
    tagline: "Putzplan, der sich an echte Nutzung anpasst",
    description:
      "Erstellt individuelle Reinigungspläne pro Raum und erinnert basierend auf Intervallen statt starren Terminen.",
    url: "https://tody.app",
    priceTier: "einmalig",
    priceDetail: "einmalig ca. 5€",
    trustScore: 74,
    sources: [{ name: "App Store", url: "https://apps.apple.com" }],
    firstSeen: "2022-05-01",
    lastUpdated: new Date().toISOString(),
    tags: ["putzplan", "organisation"],
  },
  {
    id: "mealie",
    name: "Mealie",
    categoryId: "essen",
    tagline: "Selbst gehostete Rezeptverwaltung mit Einkaufsliste",
    description:
      "Importiert Rezepte per Link, plant Mahlzeiten für die Woche und erzeugt automatisch Einkaufslisten.",
    url: "https://mealie.io",
    priceTier: "kostenlos",
    trustScore: 80,
    sources: [{ name: "GitHub", url: "https://github.com" }],
    firstSeen: "2023-09-01",
    lastUpdated: new Date().toISOString(),
    tags: ["rezepte", "planung"],
  },
  {
    id: "yuka",
    name: "Yuka",
    categoryId: "essen",
    tagline: "Lebensmittel und Kosmetik scannen und bewerten",
    description:
      "Scannt Barcodes und zeigt eine verständliche Bewertung von Inhaltsstoffen inklusive Alternativen.",
    url: "https://yuka.io",
    priceTier: "freemium",
    trustScore: 78,
    sources: [{ name: "Yuka", url: "https://yuka.io" }],
    firstSeen: "2022-01-01",
    lastUpdated: new Date().toISOString(),
    tags: ["ernährung", "scanner"],
  },
  {
    id: "komoot",
    name: "Komoot",
    categoryId: "freizeit",
    tagline: "Routenplanung für Rad- und Wandertouren",
    description:
      "Plant Touren nach Schwierigkeitsgrad und Landschaft, mit Sprachnavigation und Community-Empfehlungen.",
    url: "https://komoot.de",
    priceTier: "freemium",
    trustScore: 83,
    sources: [{ name: "Komoot", url: "https://komoot.de" }],
    firstSeen: "2021-01-01",
    lastUpdated: new Date().toISOString(),
    tags: ["outdoor", "navigation"],
  },
  {
    id: "meetup",
    name: "Meetup",
    categoryId: "freizeit",
    tagline: "Lokale Gruppen und Veranstaltungen finden",
    description:
      "Verbindet Menschen mit gemeinsamen Interessen über lokale Treffen und Gruppen.",
    url: "https://meetup.com",
    priceTier: "kostenlos",
    trustScore: 70,
    sources: [{ name: "Meetup", url: "https://meetup.com" }],
    firstSeen: "2020-01-01",
    lastUpdated: new Date().toISOString(),
    tags: ["community", "veranstaltungen"],
  },
  {
    id: "khan-kids",
    name: "Khan Academy Kids",
    categoryId: "kinder",
    tagline: "Kostenlose Lern-App für Vor- und Grundschulkinder",
    description:
      "Werbefreie, adaptive Lerninhalte in Sprache, Mathematik und Kreativität, ohne versteckte Käufe.",
    url: "https://learn.khanacademy.org/khan-academy-kids",
    priceTier: "kostenlos",
    trustScore: 90,
    sources: [{ name: "Khan Academy", url: "https://khanacademy.org" }],
    firstSeen: "2022-01-01",
    lastUpdated: new Date().toISOString(),
    tags: ["lernen", "vorschule"],
  },
  {
    id: "familonet",
    name: "Google Family Link",
    categoryId: "kinder",
    tagline: "Bildschirmzeit und App-Freigaben verwalten",
    description:
      "Setzt Nutzungszeiten, gibt Apps frei und behält den Überblick über Standort und Aktivität der Kinder.",
    url: "https://families.google/familylink",
    priceTier: "kostenlos",
    trustScore: 86,
    sources: [{ name: "Google", url: "https://families.google" }],
    firstSeen: "2021-06-01",
    lastUpdated: new Date().toISOString(),
    tags: ["kinderschutz", "bildschirmzeit"],
  },
];
